name: AppImage Build

on:
  workflow_dispatch:

jobs:
  test-package-build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:20.04
      volumes:
        - ${{ github.workspace }}:/build
      options: --privileged

    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - run: bash /build/.github/workflows/build_appimage.sh
