name: AppImage Build

on:
  workflow_dispatch:


jobs:
  docker-build:
    name: Docker build
    runs-on: ubuntu-latest
 
    container:
      image: ubuntu:20.04
      volumes:
        - ${{ github.workspace }}:/build
      options: --privileged

    steps:
      - name: Checkout
      - uses: actions/checkout@v4
      - run: bash /build/.github/workflows/build_appimage.sh
